web/app/views/cases.py
#  -*-coding:utf8-*-

################################################################################
#
#
#
################################################################################
"""
模块用法说明: URL case操作处理模块

Authors: Turinblueice
Date:
"""
from flask import Blueprint
from flask import render_template
from flask import request
from flask import Response

from case_loader import case_loader
from test_running import runner
import json
import re

from web.app.models import model_cases
from web.app.models import model_case_group
from web.app.extensions import db

cases = Blueprint('cases', __name__, template_folder='../../templates')

CASES_PER_PAGE = 4


@cases.route('/', methods=['get'])
@cases.route('/<int:group_id>/', methods=('get',))
def display(group_id=None):
    """
        Summary:
            展示case
    :return:
    """
    curr_page_num = request.args.get('page_num', '1')
    curr_page_num = int(curr_page_num) if re.match('^\d+$', curr_page_num) else 1  # 非数字则默认为1

    if group_id is None or group_id == 0:
        query_set = model_cases.Cases.query
        group_id = 0

    else:
        group = model_case_group.CaseGroups.query.filter_by(id=int(group_id)).first()
        if group is None:
            return "无该分组"

        query_set = model_cases.Cases.query.filter(model_cases.Cases.group_id == group.id)

    try:   # 如果当前页码不在分页后页码的范围内[1,Max], 则默认返回首页
        pagination = query_set.paginate(curr_page_num, CASES_PER_PAGE, True)
    except:
        pagination = query_set.paginate(1, CASES_PER_PAGE, True)

    page_number_items = _get_page_list(pagination.page, 5, pagination.pages)
    groups = model_case_group.CaseGroups.query.all()

    return render_template('case_select.html', pagination=pagination, groups=groups,
                           group_id=group_id, page_nums=page_number_items)


@cases.route('/display-json-by-group/<int:group_id>/', methods=('get',))
def display_json_by_group(group_id):
    """
    按照组别返回case列表的接口
    :param group_id:
    :return:
    """
    rsp_dic = dict(code=0)

    start = request.args.get('start', '0')
    end = request.args.get('end', '20')

    comp = re.compile(r"^\d+$")

    start = int(start) if comp.match(start) else 0
    end = int(end) if comp.match(end) else 20

    if start > end:
        start = 0

    group = model_case_group.CaseGroups.query.filter_by(id=int(group_id)).first()
    if group is None:
        rsp_dic['code'] = 2
        rsp_dic['msg'] = u"没有该分组"

    else:
        curr_group_cases = group.cases   # group通过一对多的反向代理访问cases
        curr_group_cases = curr_group_cases.slice(start, end)  # 使用slice进行分页, 自动处理start和end和总数之间的数值大小关系

        case_list = [dict(id=case.id, name=case.name) for case in curr_group_cases]
        rsp_dic['cases'] = case_list

    return Response(json.dumps(rsp_dic), content_type='application/json')


@cases.route('/display-board-by-group/<int:group_id>/', methods=('get',))
@cases.route('/display-board-by-group/<int:group_id>/<int:page_num>/', methods=('get',))
def display_by_group(group_id, page_num=None):
    """
    按照组别返回case列表展示面板
    :param group_id: 分组ID
    :param page_num: 分码序号
    :return:
    """
    curr_page_num = page_num if page_num >= 1 else 1

    group = model_case_group.CaseGroups.query.filter_by(id=int(group_id)).first()
    if group is None:
        return "无该分组"

    query_set = model_cases.Cases.query.filter(model_cases.Cases.group_id == group.id)
    pagination = query_set.paginate(curr_page_num, CASES_PER_PAGE, True)
    page_number_items = _get_page_list(pagination.page, 5, pagination.pages)

    return render_template('case_select.html', pagination=pagination, page_nums=page_number_items)


@cases.route('/cases-submit/', methods=['post'])
def cases_submit():
    """
        Summary:
            提交将要执行的case列表, 并且执行case
    :return:
    """

    test_runner = runner.test_runner  # 将单例的测试执行模块赋值到临时变量

    if not test_runner.RUNNING:

        case_str = request.form.get('cases')
        case_list = case_str.split(',')[:-1]
        origin_cases = model_cases.Cases.query.filter(model_cases.Cases.id.in_(case_list)).all()

        loader = case_loader.SQLAlchemyCaseLoader(case_list=origin_cases)
        curr_cases = loader.load()

        test_runner.init_cases(curr_cases)
        test_runner.run_async(3)
        return '测试任务已提交,请等待运行结束'

    return '请等待测试任务结束再提交新任务'


# 公共方法
def _get_page_list(curr_page, per_page_items, page_count):
    """
        获取页码列表
    :param curr_page: 当前页码
    :param per_page_items: 每页显示页码数
    :param page_count: 总页码数
    :return:
    """
    if page_count <= 0:  # 总页码数为零,则说明无任何数据展示, 展示页空白
        return [1]

    if per_page_items >= page_count:  # 避免每页显示的页数大于总页数
        per_page_items = page_count

    if per_page_items <= 0:
        per_page_items = 1

    page_num_list = list()

    start_page = curr_page - per_page_items/2
    max_page_number = curr_page + per_page_items/2
    min_page_number = curr_page - per_page_items/2
    if page_count <= max_page_number:
        start_page = page_count - per_page_items + 1
    if 0 >= min_page_number:
        start_page = 1

    for index in xrange(per_page_items):
        page_num_list.append(start_page+index)

    return page_num_list


@cases.route('/delete/', methods=('post',))
def delete():
    """
    删除case
    :return:
    """
    rsp_dic = dict(succ=False)
    case_id = request.form.get('id')

    delete_item = model_cases.Cases.query.filter_by(id=int(case_id)).first()
    if delete_item:
        delete_item.discard()
        rsp_dic['succ'] = True

    return Response(response=json.dumps(rsp_dic), content_type='application/json')


@cases.route('/update/<int:case_id>/', methods=('post', 'get'))
def update(case_id):
    """
    更改case的json接口,供ajax使用
    :param case_id: case id
    :return:
    """
    rsp_dic = dict(id=-1, info=None)
    case = model_cases.Cases.query.filter_by(id=int(case_id)).first()
    if case:
        # 有该case

        # keys = ['id', 'name', 'prior', 'description', 'url', 'method',
        #         'headers', 'params', 'data', 'cookies', 'tests', 'group_id']
        # values = map(lambda key: case.__getattribute__(key), keys)
        info_dic = case.__dict__
        del info_dic['_sa_instance_state']  # 删除case model中的非数据字段

        info_dic['cookies'] = json.loads(case.cookies) if case.cookies else dict()
        info_dic['headers'] = json.loads(case.headers) if case.headers else dict()
        info_dic['params'] = json.loads(case.params) if case.params else dict()
        info_dic['data'] = json.loads(case.data) if case.data else dict()
        rsp_dic['id'] = case.id
        rsp_dic['tests'] = ';\n'.join(case.tests.split(';')) if case.tests else ""
        rsp_dic['info'] = info_dic

    return Response(response=json.dumps(rsp_dic), content_type='application/json')


@cases.route('/update-board/<int:case_id>/', methods=('get',))
def update_on_board(case_id):
    """
    返回更新数据的模版
    :return:
    """
    case = model_cases.Cases.query.filter_by(id=int(case_id)).first()
    if case:
        groups = model_case_group.CaseGroups.query.all()

        # 将case中部分字段在数据库存储的str字符串转为相应的对象
        case.cookies = json.loads(case.cookies) if case.cookies else dict()
        case.headers = json.loads(case.headers) if case.headers else dict()
        case.params = json.loads(case.params) if case.params else dict()
        case.data = json.loads(case.data) if case.data else dict()
        case.tests = ';\n'.join(case.tests.split(';')) if case.tests else ""

        return render_template('update_processor_board.html', case=case, groups=groups)
    return '无此id为{}的case'.format(case_id)

if __name__ == "__main__":

    print _get_page_list(4, 2, 6)

web/app/views/index.py
#  -*-coding:utf8-*-

################################################################################
#
#
#
################################################################################
"""
模块用法说明: 导航页

Authors: Turinblueice
Date:
"""

from flask import Blueprint
from flask import render_template
from flask import request
from flask import Response
from utils import log
import datetime
import json
import requests
import os

index = Blueprint('index', __name__, template_folder='../../templates')


@index.route('/')
def show_index():

    # from web.app.models.model_case_group import CaseGroups
    # from web.app.models.model_cases import Cases
    #
    # groups = CaseGroups.query.all()
    # cases = groups[0].cases.all()
    #
    # case = Cases.query.filter_by(id=1).first()
    # group = case.group
    lines = [u"1. 输入网址url, 输入相应参数, 点击请求获取内容",
             u"2. 点击保存, 可以将url和相应参数保存",
             u"3. 使用JavaScript语法写自定义验证方法,如 tests[\"测试\"] = responseBody.code == 200"]

    return render_template('index.html', lines=lines)

web/app/views/processor.py
#  -*-coding:utf8-*-

################################################################################
#
#
#
################################################################################
"""
模块用法说明: URL case操作处理模块

Authors: Turinblueice
Date:
"""

from flask import Blueprint
from flask import render_template
from flask import request
from flask import Response

from web.app.models import model_cases
from web.app.models import model_case_group
from web.app.extensions import db
from custom_exceptions import exceptions as EXP
from utils import log
import datetime
import json
import requests
import re


processor = Blueprint('processor', __name__, template_folder='../../templates')


@processor.route('/', methods=('get',))
def case_process():
    """
        Summary:
            case操作页访问
    :return:
    """
    groups = model_case_group.CaseGroups.query.all()
    rsp = render_template('processor.html', groups=groups)
    return rsp


@processor.route('/upload_req/', methods=('post',))
def request_handler():
    """
        Summary:
            上传请求,获取请求后的的处理方法
    :return:
    """

    form = request.form
    url = form.get('url', None)
    method = form.get('method', None)
    headers = form.get('headers', None)
    data = form.get('data', None)
    cookies = form.get('cookies', None)

    try:
        headers = json.loads(headers.encode('utf8')) if headers else '{}'
        data = json.loads(data.encode('utf8')) if headers else '{}'
        cookies = json.loads(cookies.encode('utf8')) if cookies else '{}'
    except ValueError:
        log.logger.error("传入的数据非json格式")

    # 发送请求,获取请求结果
    rsp = _make_request(method, url, data, headers, cookies)

    # 获取返回response的cookie
    cookies = dict()
    rsp_cookies = rsp.cookies
    for cookie in rsp_cookies:
        cookies[cookie.name] = {}
        cookies[cookie.name]['name'] = cookie.name
        cookies[cookie.name]['value'] = cookie.value
        cookies[cookie.name]['domain'] = cookie.domain
        cookies[cookie.name]['path'] = cookie.path
        cookies[cookie.name]['expires'] = datetime.datetime.fromtimestamp(cookie.expires).strftime("%Y-%m-%d %H:%M:%S") \
            if cookie.expires else ''
        cookies[cookie.name]['secure'] = cookie.secure
        cookies[cookie.name]['httponly'] = False if not cookie.has_nonstandard_attr('httponly') else cookie.httponly

    # 获取header信息
    headers = dict(rsp_header=rsp.headers)

    content = rsp.text  # 获取返回的文本string, 非二进制byte流
    content_type = rsp.headers['content-type']

    curr_rsp = Response(content, content_type=content_type)
    curr_rsp.headers.add('rsp-cookie', _to_string(cookies))
    curr_rsp.headers.add('rsp-header', _to_string(headers))

    return curr_rsp


@processor.route('/save_request/', methods=['post'])
def save_request():
    """
        Summary:
            将请求保存到数据库, 包含新增和修改case的保存
    :return:
    """
    forms = request.form.items()
    status_dic = dict(code=0)
    try:
        forms = map(_check_form, forms)
        forms = dict(forms)

        group = forms['group']
        if model_case_group.CaseGroups.query.filter_by(name=group).first() is None:
            #  新增分组
            new_group = model_case_group.CaseGroups(name=group)
            new_group.save()

        group_id = model_case_group.CaseGroups.query.filter_by(name=group).first().id

        if 'id' in forms:  # 更改case
            if re.match('^\d+$', forms['id']):
                case_id = int(forms['id'])
                case_item = model_cases.Cases.query.filter_by(id=case_id).first()

                case_item.id = case_id
                case_item.name = forms['name']
                case_item.group_id = group_id
                case_item.prior = forms['prior']
                case_item.params = forms['params']
                case_item.description = forms['description']
                case_item.url = forms['url']
                case_item.method = forms['method']
                case_item.headers = forms['headers']
                case_item.data = forms['data']
                case_item.cookies = forms['cookies']
                case_item.tests = forms['tests']

                case_item.commit()

        else:  # 新增case
            case_item = model_cases.Cases(name=forms['name'], group_id=group_id, description=forms['description'],
                                          prior=forms['prior'], url=forms['url'], method=forms['method'],
                                          headers=forms['headers'], data=forms['data'], cookies=forms['cookies'],
                                          tests=forms['tests'])
            case_item.save(False)

        return Response(response=json.dumps(status_dic), content_type='application/json')

    except Exception as exp:

        status_dic["code"] = 1
        status_dic["msg"] = str(exp)
        return Response(response=json.dumps(status_dic), content_type='application/json')


@processor.route("/get_groups/", methods=['get'])
def get_groups():
    """
        Summary:
            获取所有分组
    :return:
    """
    groups = model_case_group.CaseGroups.query.all()
    group_infos = map(lambda group: dict(id=group.id, name=group.name), groups)
    group_dict = dict(groups=group_infos)

    return Response(response=json.dumps(group_dict), content_type='application/json')


# 以下为公共方法
def _make_request(method, url, data, headers, cookies):
    """
        Summary:
            构建一个请求
    :param method: 请求方法get/post/put/delete
    :param url: 连接
    :param data: post方法方法体传递的数据
    :param headers: 消息头
    :param cookies: cookie
    :return: 返回response
    """
    rsp = requests.request(method, url, data=data, headers=headers, cookies=cookies)

    return rsp


def _to_string(key_dict):
    """
        Summary:
            字典转化为字符串,字典格式为{key:{}}的格式,如
            把{name1:{name:xx,value:xx,domain:dd},
            name2:{name:xx,value:xx,domain:dd}} 转化成name@xx&value@xx&domain@dd|name@xx&value@xx&domain@dd
    :param key_dict:
    :return:
    """
    dict_str = ''
    for outer_key, outer_value in key_dict.iteritems():
        for key in outer_value:
            str_slice = str(key)+'@'+str(outer_value[key])
            dict_str += str_slice
            dict_str += '&'
        dict_str = dict_str[:-1]
        dict_str += '|'
    dict_str = dict_str[:-1]
    return dict_str


def _check_form((key, value)):
    """
        Summary:
            检查表单返回数据
        Args:
            key: 表单键
            value: 表单值
        Return:
            返回字符串或者None
    """
    if isinstance(value, unicode):
        return key, value
    elif isinstance(value, str):
        return key, value.decode('utf8')  # 解析成unicode串保存
    raise EXP.FormValueError("参数"+key+"传递错误,应为unicode或者string类型")

web/app/views/report_square.py
#  -*-coding:utf8-*-

################################################################################
#
#
#
################################################################################
"""
模块用法说明: 报告列表广场

Authors: Turinblueice
Date:
"""

from flask import Blueprint
from flask import render_template
from flask import request
from flask import Response
import os
import re
import datetime


report_square = Blueprint('report_square', __name__, template_folder='../../templates')


@report_square.route('/', methods=('get',))
def show_report_square():
    """
    展示测试报告广场面板, 访问各个列表
    :return:
    """
    start_time = request.args.get('start', None)
    end_time = request.args.get('end', None)

    if start_time is None or end_time is None:
        today = datetime.datetime.today()
        week_ago = today - datetime.timedelta(days=6)
        end_time = today.strftime('%Y%m%d')
        start_time = week_ago.strftime('%Y%m%d')

    regex_comp = re.compile(r'\d{8}')
    if regex_comp.match(start_time) is None:
        return "开始时间格式错误,应该为8位数字"
    if regex_comp.match(end_time) is None:
        return "结束时间格式错误,应该为8位数字"

    report_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), '../../../outputs/report')
    )

    report_dirs = filter(lambda report_dir: report_dir not in ['index', 'static'] and report_dir >= start_time and report_dir <= end_time,
                         os.listdir(report_path))

    report_urls_dic = dict()

    for report_dir in report_dirs:
        report_urls_dic[report_dir] = list()
        for url in os.listdir(os.path.join(report_path, report_dir)):
            timestamp = url[7:-5]
            report_urls_dic[report_dir].append(timestamp)

    return render_template('report_square.html', report_urls_dic=report_urls_dic)

web/templates/case_select.html
{% extends "layout.html" %}
{% block title %}用例查看展示面板{% endblock %}
{% block js_path %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/cases.js') }}"></script>
    <script type="text/javascript">

        $(document).ready(function(){
            initSideBar();
        })

    </script>
{% endblock %}
{% block css_path %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/case-select.css') }}">
{% endblock %}
{% block body %}
    <div class="group-select">
        <div class="case-description">选择分组展示case:</div>
        <select class="case-group-select">
            <option value="0" {%if 0 == group_id%}selected="selected"{%endif%}>所有case</option>
            {% for group in groups %}
                <option value="{{group.id}}" {%if group.id == group_id%}selected="selected"{%endif%}>{{group.name}}</option>
            {% endfor %}
        </select>
    </div>

    <div class="case-board">
        {% for case in pagination.items %}
        <div class="case-wrapper">
            <div class="case-info">
                <input type="checkbox" class="option-input" name="case" value={{case.id}}>
                {{case.name}}<span class="url">{{case.url}}</span>
            </div>
            <div class="case-update"><a href="/cases/update-board/{{case.id}}/" target="_blank" class="update"></a></div>
            <div class="case-delete"><button class="delete"></button></div>
        </div>

        {% endfor %}
        <button id="btn-submit">提交</button>
    </div>
    <div class="page-items">
        {% if pagination.page > 1 %}
            <div class="page-item page-item-side">
                <a href="{{url_for('cases.display', group_id=group_id, page_num=pagination.page-1)}}">上一页</a>
            </div>
        {% endif %}
        {% for page_num in page_nums %}
            <div class="page-item {% if page_num == pagination.page %}current-page{% endif %}">
                <a href="{{url_for('cases.display', group_id=group_id, page_num=page_num)}}">{{page_num}}</a>
            </div>
        {% endfor %}
        {% if pagination.page < pagination.pages %}
            <div class="page-item page-item-side">
                <a href="{{url_for('cases.display', group_id=group_id, page_num=pagination.page+1)}}">下一页</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

web/templates/index.html
{% extends "layout.html" %}
{% block title %}用例查看展示面板{% endblock %}
{% block js_path %}
    <!-- <script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script> -->
    <script type="text/javascript">

        $(document).ready(function(){
            initSideBar();
        })

    </script>
{% endblock %}
{% block css_path %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}
{% block body %}
<div class="index-wrapper">
    <div class="title">用法介绍</div>
    <div class="content">
        {% for line in lines %}
            <div class="line">{{line}}</div>
        {% endfor %}
    </div>
</div>

{% endblock %}

web/templates/layout.html
<!--总网页模版 -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title%}{% endblock %}</title>
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-2.1.4.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/util.js') }}"></script>
        {% block js_path %}{% endblock %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/layout.css')}}">
        {% block css_path %}{% endblock %}

    </head>
    <body>
        <div class="side-bar"> <!-- 侧边栏-->
            <div>
                <div class="curr-page" id="index"><a href="{{ url_for('index.show_index') }}">回到主页</a></div>
                <div id="addCase"><a href="{{ url_for('processor.case_process') }}">新增接口</a></div>
                <!-- <div><a href="{{ url_for('report_square.show_report_square') }}">修改接口</a></div> -->
                <div id="caseSelect"><a href="{{ url_for('cases.display', page_num=1) }}">用例展示</a></div>
                <div id="reportSquare"><a href="{{ url_for('report_square.show_report_square') }}">报告广场</a></div>
            </div>
        </div>
        <div class="body-wrapper">
            {% block body%}
            {% endblock %}
        </div>
    </body>
</html>

web/templates/layout_no_sidebar.html
<!--总网页模版 -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title%}{% endblock %}</title>
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-2.1.4.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/util.js') }}"></script>
        {% block js_path %}{% endblock %}
        <!--<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/layout.css')}}">-->
        {% block css_path %}{% endblock %}

    </head>
    <body>
        <!--<div class="side-bar"> -->
            <!--<div>-->
                <!--<div class="curr-page" id="index"><a href="{{ url_for('index.show_index') }}">回到主页</a></div>-->
                <!--<div id="addCase"><a href="{{ url_for('processor.case_process') }}">新增接口</a></div>-->
                <!--&lt;!&ndash; <div><a href="{{ url_for('report_square.show_report_square') }}">修改接口</a></div> &ndash;&gt;-->
                <!--<div id="caseSelect"><a href="{{ url_for('cases.display', page_num=1) }}">用例展示</a></div>-->
                <!--<div id="reportSquare"><a href="{{ url_for('report_square.show_report_square') }}">报告广场</a></div>-->
            <!--</div>-->
        <!--</div> -->
        <div class="body-wrapper">
            {% block body%}
            {% endblock %}
        </div>
    </body>
</html>

web/templates/report_square.html
{% extends "layout.html" %}
{% block title %}测试报告广场列表-最近七天{% endblock %}
{% block js_path %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/report-square.js') }}"></script>
    <script type="text/javascript">

        $(document).ready(function(){
            initSideBar();
        })

    </script>
{% endblock %}
{% block css_path %}
    <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/report-square.css') }}"> -->
{% endblock %}
{% block body %}
    {% for report_time in report_urls_dic %}
        <div class="report">
            <div class="report-time">{{report_time}}</div>
            <div class="report-urls">
                {% for url in report_urls_dic[report_time] %}
                    <div class="report-url"><a href="{{ url_for('report.show_date_report', date=url[0:8], time=url) }}"}
                     target="_blank">
                        {{url}}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock %}